/*
 * Copyright (C) 2015 ~ 2018 Deepin Technology Co., Ltd.
 *
 * Author:     Hualet Wang <mr.asianwang@gmail.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c MenuAdaptor -a dbus_menu_adaptor.h:dbus_menu_adaptor.cpp com.deepin.menu.Menu.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUS_MENU_ADAPTOR_H_1405666344
#define DBUS_MENU_ADAPTOR_H_1405666344

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.menu.Menu
 */
class MenuAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.menu.Menu")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.menu.Menu\">\n"
"    <method name=\"ShowMenu\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"menuJsonContent\"/>\n"
"    </method>\n"
"    <method name=\"SetItemActivity\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"itemId\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"isActive\"/>\n"
"    </method>\n"
"    <method name=\"SetItemChecked\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"itemId\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"checked\"/>\n"
"    </method>\n"
"    <method name=\"SetItemText\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"itemId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\"/>\n"
"    </method>\n"
"    <signal name=\"ItemInvoked\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"itemId\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"checked\"/>\n"
"    </signal>\n"
"    <signal name=\"MenuUnregistered\"/>\n"
"  </interface>\n"
        "")
public:
    MenuAdaptor(QObject *parent);
    virtual ~MenuAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void SetItemActivity(const QString &itemId, bool isActive);
    void SetItemChecked(const QString &itemId, bool checked);
    void SetItemText(const QString &itemId, const QString &text);
    void ShowMenu(const QString &menuJsonContent);
Q_SIGNALS: // SIGNALS
    void ItemInvoked(const QString &itemId, bool checked);
    void MenuUnregistered();
};

#endif
